# Generated by Django 3.1.1 on 2020-09-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='review_car',
        ),
    ]
